Nss complaint
DevCom-IITB/instiapp-api pull request #209
Opened 2018-09-05 07:04 UTC by sshivam95

2018-09-05 16:59 UTC, pulsejet requested changes
A few notes:
1) You'll need to add test cases for all APIs
2) Merge all migrations once everything looks right
3) Some general issues reported by Codacy should be fixed.
I don't have time right now to test this; will do it as soon as possible.

2018-09-05 16:59 UTC, pulsejet commented on .idea/IITBapp.iml
> +</module>
Don't commit IDE specific folders (.idea)

2018-09-05 16:59 UTC, pulsejet commented on backend/settings_base.py
> +    'venter',
`venter.apps.VenterConfig` instead of just `venter`. This is the new convention.

2018-09-05 16:59 UTC, pulsejet commented on backend/urls.py
> +import venter
Why?

2018-09-05 16:59 UTC, pulsejet commented on backend/urls.py
>      path('api/bodies/<pk>', BodyViewSet.as_view(
No unnecessary whitespace changes please; make a separate PR to master for this if necessary.

2018-09-05 16:59 UTC, pulsejet commented on backend/urls.py
> +    ##
Remove the `##`

2018-09-05 16:59 UTC, pulsejet commented on bodies/admin.py
> +admin.site.register(Body, BodyAdmin)
Why do we need these changes?

2018-09-05 16:59 UTC, pulsejet commented on venter/models.py
> +        # class complaints_liked_users(models.Model):
No commented code please. See [this](https://softwareengineering.stackexchange.com/questions/190096/can-commented-out-code-be-valuable-documentation) thread.

2018-09-05 16:59 UTC, pulsejet commented on venter/serializers.py
> +    # media = serializers.SlugRelatedField(many=True, read_only=True, slug_field='picture', source='media')
No commented code, again

2018-09-05 16:59 UTC, pulsejet commented on venter/views.py
> +from .models import complaints
Use `venter.models` and similar instead of just `.models`

2018-09-05 17:05 UTC, sshivam95 commented
Noted.

FYI I haven't changed anything in the bodies/admin.py, it may be because of
the previous commit when i cloned the repo.

Regards
Shivam Sharma

On Sep 5, 2018 10:29 PM, "Varun Patil" <notifications@github.com> wrote:

> *@pulsejet* requested changes on this pull request.
>
> A few notes:
>
>    1. You'll need to add test cases for all APIs
>    2. Merge all migrations once everything looks right
>    3. Some general issues reported by Codacy should be fixed.
>    I don't have time right now to test this; will do it as soon as
>    possible.
>
> ------------------------------
>
> In .idea/IITBapp.iml
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215347865>:
>
> > +    <content url="file://$MODULE_DIR$" />
> +    <orderEntry type="inheritedJdk" />
> +    <orderEntry type="sourceFolder" forTests="false" />
> +  </component>
> +  <component name="TemplatesService">
> +    <option name="TEMPLATE_CONFIGURATION" value="Django" />
> +    <option name="TEMPLATE_FOLDERS">
> +      <list>
> +        <option value="$MODULE_DIR$/prerender/templates" />
> +      </list>
> +    </option>
> +  </component>
> +  <component name="TestRunnerService">
> +    <option name="PROJECT_TEST_RUNNER" value="Unittests" />
> +  </component>
> +</module>
>
> Don't commit IDE specific folders (.idea)
> ------------------------------
>
> In backend/settings_base.py
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215348270>:
>
> > @@ -35,7 +35,7 @@
>      'news.apps.NewsConfig',
>      'messmenu.apps.MessmenuConfig',
>      'other.apps.OtherConfig',
> -
> +    'venter',
>
> venter.apps.VenterConfig instead of just venter. This is the new
> convention.
> ------------------------------
>
> In backend/urls.py
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215348398>:
>
> >  from rest_framework_swagger.views import get_swagger_view
>
> +import venter
>
> Why?
> ------------------------------
>
> In backend/urls.py
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215348572>:
>
> > @@ -34,74 +35,77 @@
>  urlpatterns = [
>      path('admin/', admin.site.urls),
>
> -    path('api/bodies', BodyViewSet.as_view({'get':'list', 'post':'create'})),
> +    path('api/bodies', BodyViewSet.as_view({'get': 'list', 'post': 'create'})),
>      path('api/bodies/<pk>', BodyViewSet.as_view(
>
> No unnecessary whitespace changes please; make a separate PR to master for
> this if necessary.
> ------------------------------
>
> In backend/urls.py
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215348712>:
>
> >
>      path('api/mess', get_mess),
>
> -    path('api/search', OtherViewset.as_view({'get':'search'})),
> -    path('api/notifications', OtherViewset.as_view({'get':'get_notifications'})),
> -    path('api/notifications/read', OtherViewset.as_view({'get':'mark_all_notifications_read'})),
> -    path('api/notifications/read/<pk>', OtherViewset.as_view({'get':'mark_notification_read'})),
> +    path('api/search', OtherViewset.as_view({'get': 'search'})),
> +    path('api/notifications', OtherViewset.as_view({'get': 'get_notifications'})),
> +    path('api/notifications/read', OtherViewset.as_view({'get': 'mark_all_notifications_read'})),
> +    path('api/notifications/read/<pk>', OtherViewset.as_view({'get': 'mark_notification_read'})),
> +    ##
>
> Remove the ##
> ------------------------------
>
> In bodies/admin.py
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215348853>:
>
> >
> -admin.site.register(Body)
> +class RoleInline(admin.StackedInline):
> +    model = BodyRole
> +    fields = ('name',)
> +    readonly_fields = ('name',)
> +    show_change_link = True
> +
> +class BodyAdmin(admin.ModelAdmin):
> +    inlines = [RoleInline]
> +
> +admin.site.register(Body, BodyAdmin)
>
> Why do we need these changes?
> ------------------------------
>
> In venter/models.py
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215349093>:
>
> > +class comment(models.Model):
> +    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
> +    time = models.DateTimeField(default=now)
> +    text = models.TextField()
> +    user = models.ForeignKey('users.UserProfile', on_delete=models.CASCADE)
> +    complaint = models.ForeignKey(complaints, on_delete=models.CASCADE, related_name="comments")
> +
> +    class Meta:
> +        verbose_name = "Comment"
> +        verbose_name_plural = "Comments"
> +
> +    def __str__(self):
> +        return self.text
> +
> +
> +        # class complaints_liked_users(models.Model):
>
> No commented code please. See this
> <https://softwareengineering.stackexchange.com/questions/190096/can-commented-out-code-be-valuable-documentation>
> thread.
> ------------------------------
>
> In venter/serializers.py
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215349156>:
>
> > +    comments = CommentSerializer(many=True)  # related name (comments)
> +    media = UploadedImageSerializer(many=True)
> +
> +    class Meta:
> +        model = complaints
> +        fields = '__all__'
> +
> +
> +class ComplaintPostSerializer(serializers.ModelSerializer):
> +    tags = TagSerializer(many=True, read_only=True)
> +    tag_names = serializers.SlugRelatedField(many=True, read_only=True, slug_field='tag_uri', source='tags')
> +    tag_ids = serializers.PrimaryKeyRelatedField(many=True, read_only=False, source='tags',
> +                                                 queryset=tag_uris.objects.all(), required=True)
> +
> +    media = UploadedImageSerializer(many=True, read_only=True)
> +    # media = serializers.SlugRelatedField(many=True, read_only=True, slug_field='picture', source='media')
>
> No commented code, again
> ------------------------------
>
> In venter/views.py
> <https://github.com/wncc/IITBapp/pull/209#discussion_r215349448>:
>
> > @@ -0,0 +1,28 @@
> +from coreapi.exceptions import ParseError
> +from django.shortcuts import render
> +
> +# Create your views here.
> +from rest_framework.decorators import detail_route, action
> +
> +from .models import complaints
>
> Use venter.models and similar instead of just .models
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wncc/IITBapp/pull/209#pullrequestreview-152591892>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AZWUcrOe_hOSuEjySvYYtHD32l2yDwPIks5uYALngaJpZM4WaTLF>
> .
>

2018-09-05 18:01 UTC, pulsejet commented
Yes, those changes are probably from b23891d59768f2990f10fe66e2a67f700300f89b. Just revert them.

2018-09-17 12:52 UTC, pulsejet approved these changes

2018-09-17 13:01 UTC, pulsejet commented
Closing this in favour of #211

2018-09-17 13:01 UTC, closed without merging