Implement Length Penalty
DevCom-IITB/instiapp-api pull request #269
Opened 2018-10-06 13:11 UTC by HrushikeshBodas

Added the length penalty which is a overall multiplying factor

2018-10-06 13:13 UTC, HrushikeshBodas commented
Solves #257

2018-10-06 16:02 UTC, pulsejet requested changes

2018-10-06 16:02 UTC, pulsejet commented on events/prioritizer.py
> +    event.weight *= length_penalty
This needs more indent, `event` isn't defined outside the loop. Check failing test cases. Also add a whitespace between `#` and the comment.

2018-10-07 18:08 UTC, pulsejet approved these changes

2018-10-07 18:09 UTC, pulsejet commented
Good work @HrushikeshBodas!

2018-10-07 18:10 UTC, merged